services:
  - type: web
    name: bikroy-intelligence
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd website && gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0