services:
  - type: web
    name: Bikroy_Price_Intelligence
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn website.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_SECRET_KEY
        value: YOUR_SECRET_KEY_HERE
      - key: SENDER_EMAIL
        value: YOUR_EMAIL_HERE
      - key: SENDER_PASSWORD
        value: YOUR_EMAIL_PASSWORD_HERE
